### ISSUE TITLE
rethinkdbdash implementation

### ISSUE THREAD

**Issue by paramaggarwal** [1N50MN14/emitter-rethinkdb#1]
Hello, I used this library as a starting point for making https://github.com/myntra/emitter-rethinkdb, which exclusively uses `rethinkdbdash` for its simplicity and a few other modifications that I needed.

**Comment by 1N50MN14** [comment]
@paramaggarwal Thank you for the notice. I'm not sure how you forked the package (copy/paste?) but your github doesn't show "Forked from 1N50MN14/emitter-rethinkdb" - I really don't care all that much but because git preserves history other users might think I'm related repo as you can already see here https://github.com/myntra/emitter-rethinkdb/issues/2 where the user thinks I'm involved in your code and pinging me directly.

Kindly fix this this issue. Thank you.

**Comment by paramaggarwal** [comment]
Sorry about this. I have fixed it by using Github's 'fork' construct - so that people know it is just a fork. Thanks.
